name: Deploy to EC2

on: # As trigger I need that when the docker-image workflow has finished 
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Prepare SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Pull and restart container on EC2
        run: |
          ssh -i ~/.ssh/ec2_key "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" << 'EOF'
            set -e
            IMAGE="${{ secrets.DOCKERHUB_IMAGE }}:latest"

            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker pull "$IMAGE"

            docker rm -f awstest-backend || true
            docker run -d \
              --name awstest-backend \
              --restart unless-stopped \
              -p 8080:8080 \
              "$IMAGE"
          EOF